[package]
name = "transport-webserial"
version = "0.1.0"
edition = "2021"

[dependencies]
core-types = { path = "../core-types" }
web-sys = { version = "0.3", features = ["Serial", "SerialPort", "SerialOptions"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
