[package]
name = "dec-mavlink"
version = "0.1.0"
edition = "2021"

[dependencies]
core-types = { path = "../../core-types" }
mavlink = { version = "0.12", default-features = false, features = ["common", "serde", "std"] }
embedded-hal = "0.2"
nb = "1.0"
